# Generated by Django 2.0.1 on 2019-08-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_fruitcartentity'),
        ('orderapp', '0002_auto_20190828_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=20, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收货人手机')),
                ('receiver_address', models.TextField(verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '收货地址表',
                'verbose_name_plural': '收货地址表',
                'db_table': 'order_address',
            },
        ),
        migrations.CreateModel(
            name='OrderPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cnt', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('pay_type', models.IntegerField(choices=[(0, '余额支付'), (1, '银行卡支付'), (2, '微信支付'), (3, '支付宝支付')], default=0, verbose_name='支付方式')),
                ('pay_status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '待收货'), (3, '已收货'), (4, '完成'), (5, '取消')], default=0, verbose_name='订单状态')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FruitEntity', verbose_name='水果')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 't_order_part',
            },
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='last_time',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pay_status',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receiver_address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receiver_phone',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpart',
            name='num_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderAddress', verbose_name='收货地址'),
            preserve_default=False,
        ),
    ]
