# Generated by Django 2.0.1 on 2019-08-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_orderaddress_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpart',
            name='price',
        ),
    ]
