# Generated by Django 2.0.1 on 2019-08-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='phone',
            field=models.IntegerField(max_length=11, verbose_name='电话'),
        ),
    ]
