# Generated by Django 2.0.1 on 2019-08-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_realprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='登陆用户'),
        ),
    ]
