# Generated by Django 2.0.1 on 2019-08-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190826_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruitimageentty',
            options={'verbose_name': '水果图片', 'verbose_name_plural': '水果图片'},
        ),
    ]
