# Generated by Django 2.0.1 on 2019-08-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190826_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeentity',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='last_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='最后变更时间'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='store_type',
            field=models.IntegerField(choices=[(0, '自营'), (1, '第三方')], db_column='type_', default=1, verbose_name='店类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='city',
            field=models.CharField(db_index=True, max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='店号'),
        ),
        migrations.RemoveField(
            model_name='storeentity',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='storeentity',
            name='lon',
        ),
        migrations.AlterUniqueTogether(
            name='storeentity',
            unique_together={('name', 'city')},
        ),
    ]
