# Generated by Django 2.0.1 on 2019-08-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190827_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='5a9bf53a0ab04dbaa63a284f3f69ca3a', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
