# Generated by Django 2.0.1 on 2019-08-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190827_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='8b0aa451d6b642eba112a1631f833ca6', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
