# Generated by Django 2.0.1 on 2019-08-29 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_fruitentity_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名')),
                ('order_num', models.IntegerField(default=0, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'db_table': 't_tag',
            },
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='mainapp.CateTypeEntity'),
        ),
        migrations.AddField(
            model_name='tagentity',
            name='fruits',
            field=models.ManyToManyField(db_table='t_tag_fruit', to='mainapp.FruitEntity', verbose_name='水果'),
        ),
    ]
