# Generated by Django 2.0.1 on 2019-08-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190827_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(default='449c8c9db5dc4bb9973dd9ee6a7076a9', primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
