# Generated by Django 2.0.1 on 2019-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190829_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagentity',
            options={'ordering': ['-order_num'], 'verbose_name': '标签表', 'verbose_name_plural': '标签表'},
        ),
        migrations.RemoveField(
            model_name='tagentity',
            name='fruits',
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='tags',
            field=models.ManyToManyField(db_table='t_fruit_tag', related_name='fruits', to='mainapp.TagEntity', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tagentity',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='tagentity',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='标签序号'),
        ),
    ]
