# Generated by Django 2.0.1 on 2019-08-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190827_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeentity',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='成立时间'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='店号'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='last_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='最后变更时间'),
        ),
    ]
