# Generated by Django 2.0.1 on 2019-08-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190829_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitimageentty',
            name='fruit_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='mainapp.FruitEntity'),
        ),
    ]
